products_info = {
    'Coca Cola Sin Azúcar': {'product_id': 'P001', 'unit_price': 18},
    'Fiber One Brownies': {'product_id': 'P002', 'unit_price': 57},
    'Pan Integral Bimbo': {'product_id': 'P003', 'unit_price': 56},
    'Pepsi Light': {'product_id': 'P004', 'unit_price': 17},
    'Chicles Trident': {'product_id': 'P005', 'unit_price': 10},
    'Jugo de Naranja Jumex': {'product_id': 'P006', 'unit_price': 25},
    'Yogur Griego Oikos': {'product_id': 'P007', 'unit_price': 20},
    'Leche Deslactosada Alpura': {'product_id': 'P008', 'unit_price': 22},
    'Galletas Oreo': {'product_id': 'P009', 'unit_price': 30},
    'Mantequilla Lala': {'product_id': 'P010', 'unit_price': 50},
    'Atún Dolores': {'product_id': 'P011', 'unit_price': 35},
    'Arroz SOS': {'product_id': 'P012', 'unit_price': 15},
    'Aceite de Oliva Carbonell': {'product_id': 'P013', 'unit_price': 70},
    'Café Soluble Nescafé': {'product_id': 'P014', 'unit_price': 45},
    'Azúcar Morena Zulka': {'product_id': 'P015', 'unit_price': 28},
    'Sal de Mar La Fina': {'product_id': 'P016', 'unit_price': 12},
    'Cereal Kellogg\'s Corn Flakes': {'product_id': 'P017', 'unit_price': 40},
    'Jabón de Tocador Dove': {'product_id': 'P018', 'unit_price': 25},
    'Shampoo Pantene': {'product_id': 'P019', 'unit_price': 55},
    'Pasta de Dientes Colgate': {'product_id': 'P020', 'unit_price': 32},
    'Papel Higiénico Pétalo': {'product_id': 'P021', 'unit_price': 60},
    'Detergente Ariel': {'product_id': 'P022', 'unit_price': 65},
    'Suavizante de Telas Downy': {'product_id': 'P023', 'unit_price': 58},
    'Desodorante Rexona': {'product_id': 'P024', 'unit_price': 37},
    'Crema Corporal Nivea': {'product_id': 'P025', 'unit_price': 47},
    'Arroz La Merced': {'product_id': 'P026', 'unit_price': 16},
    'Frijoles La Sierra': {'product_id': 'P027', 'unit_price': 24},
    'Huevo San Juan': {'product_id': 'P028', 'unit_price': 50},
    'Queso Panela Lala': {'product_id': 'P029', 'unit_price': 40},
    'Jamón de Pavo Fud': {'product_id': 'P030', 'unit_price': 55},
    'Tortillas de Maíz Maseca': {'product_id': 'P031', 'unit_price': 12},
    'Café Molido Blasón': {'product_id': 'P032', 'unit_price': 48},
    'Refresco Sprite': {'product_id': 'P033', 'unit_price': 18},
    'Helado Holanda': {'product_id': 'P034', 'unit_price': 60},
    'Salsa Catsup Heinz': {'product_id': 'P035', 'unit_price': 25},
    'Mostaza French\'s': {'product_id': 'P036', 'unit_price': 23},
    'Mayonesa McCormick': {'product_id': 'P037', 'unit_price': 28},
    'Pan Blanco Bimbo': {'product_id': 'P038', 'unit_price': 34},
    'Galletas Marías Gamesa': {'product_id': 'P039', 'unit_price': 18},
    'Jugo de Manzana Del Valle': {'product_id': 'P040', 'unit_price': 27},
    'Queso Oaxaca Lala': {'product_id': 'P041', 'unit_price': 65},
    'Cereal Zucaritas Kellogg\'s': {'product_id': 'P042', 'unit_price': 50},
    'Té Lipton': {'product_id': 'P043', 'unit_price': 30},
    'Agua Mineral Peñafiel': {'product_id': 'P044', 'unit_price': 15},
    'Pizza Congelada Nestlé': {'product_id': 'P045', 'unit_price': 85},
    'Sopa Maruchan': {'product_id': 'P046', 'unit_price': 12},
    'Gelatina D\'Gari': {'product_id': 'P047', 'unit_price': 10},
    'Café Latte Starbucks': {'product_id': 'P048', 'unit_price': 50},
    'Chocolate Abuelita': {'product_id': 'P049', 'unit_price': 35},
    'Papas Sabritas': {'product_id': 'P050', 'unit_price': 20},
    'Coca Cola Original': {'product_id': 'P051', 'unit_price': 18},
    'Coca Cola Light': {'product_id': 'P052', 'unit_price': 18},
    'Coca Cola Zero': {'product_id': 'P053', 'unit_price': 18},
    'Coca Cola Sin Cafeína': {'product_id': 'P054', 'unit_price': 18},
    'Coca Cola Cherry': {'product_id': 'P055', 'unit_price': 18},
    'Coca Cola Vainilla': {'product_id': 'P056', 'unit_price': 18},
    'Coca Cola Stevia': {'product_id': 'P057', 'unit_price': 18},
    'Mermelada de Fresa La Costeña': {'product_id': 'P086', 'unit_price': 32},
    'Miel de Abeja El Piquín': {'product_id': 'P087', 'unit_price': 45},
    'Avena Quaker': {'product_id': 'P088', 'unit_price': 22},
    'Granola Kellogg\'s': {'product_id': 'P089', 'unit_price': 35},
    'Cereal Choco Krispis Kellogg\'s': {'product_id': 'P090', 'unit_price': 40},
    'Cereal Froot Loops Kellogg\'s': {'product_id': 'P091', 'unit_price': 42},
    'Sardinas La Sirena': {'product_id': 'P092', 'unit_price': 28},
    'Lentejas La Costeña': {'product_id': 'P093', 'unit_price': 20},
    'Garbanzo La Costeña': {'product_id': 'P094', 'unit_price': 20},
    'Chícharos Del Monte': {'product_id': 'P095', 'unit_price': 18},
    'Maíz Pozolero Juanita\'s': {'product_id': 'P096', 'unit_price': 30},
    'Purina Dog Chow': {'product_id': 'P097', 'unit_price': 80},
    'Whiskas Gatos': {'product_id': 'P098', 'unit_price': 90},
    'Café Descafeinado Nescafé': {'product_id': 'P099', 'unit_price': 45},
    'Atole Maizena': {'product_id': 'P100', 'unit_price': 12},
    'Cocoa Hershey\'s': {'product_id': 'P101', 'unit_price': 50},
    'Cajeta Coronado': {'product_id': 'P102', 'unit_price': 38}
}